package com.talentmatch.ai;

import java.util.Map;
import java.util.UUID;

/**
 * Explanations for one page of matches.
 *
 * @param byCandidate one result per candidate on the page
 * @param generated   AI explanations generated by flights this request started
 */
public record ExplanationBatch(Map<UUID, ExplanationResult> byCandidate, int generated) {

    public ExplanationBatch {
        byCandidate = Map.copyOf(byCandidate);
    }
}
